music/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    #/music/
    url(r'^$',views.index,name='index'),
    #/music/45/
    url(r'^(?P<album_id>[0-9]+)/$',views.detail,name='detail'),
]

musicsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^music/',include('music.urls')),
    url(r'^admin/', admin.site.urls),
]

music/models.py
from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre=models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.artist + '-' + self.album_title


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type=models.CharField(max_length=10)
    song_title=models.CharField(max_length=250)

    def __str__(self):
        return self.song_title

music/views.py
from django.http import HttpResponse,Http404
from .models import Album
from django.shortcuts import render
from django.template import loader

def index(request):
     all_albums= Album.objects.all()
     context = {'all_albums': all_albums }
     return render(request, 'music/index.html', context)


def detail(request, album_id):
    try:
        album = Album.objects.get(pk=album_id)
    except Album.DoesNotExist:
        raise Http404("Album does not exist")
    return render(request, 'music/detail.html', {'album': album})

# can use this code also

#def index(request):
#    all_albums = Album.objects.all()
#    template = loader.get_template('music/index.html')
#    context = {
#        'all_albums': all_albums,
#    }
#    return HttpResponse(template.render(context, request))

music/templates/music/detail.html
<img src = "{{ album.album_logo }}">

<h1>{{album.album_title}}</h1>
<h2>{{album.artist}}</h2>

<ul>
    {% for song in album.song_set.all %}
    <li> {{song.song_title}} - {{song.file_type}}</li>
    {% endfor %}
</ul>

music/templates/music/index.html
{% if all_albums %}
   <ul>
    <h1> These are the music files avaliable</h1>
    {% for album in all_albums %}
    <li><a href="/music/{{album.id}}/">{{album.album_title}}</a> </li>
    {% endfor %}
   </ul>
{% else %}
    <h3>you don't have any albums</h3>
{% endif %}